// <auto-generated />
using System;
using DH_VehicleInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DH_VehicleInventory.Infrastructure.Migrations
{
    [DbContext(typeof(DH_InventoryDbContext))]
    [Migration("20260317091601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DH_VehicleInventory.Domain.VehicleAggregate.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("DH_Inventories", (string)null);
                });

            modelBuilder.Entity("DH_VehicleInventory.Domain.VehicleAggregate.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("DH_Vehicles", (string)null);
                });

            modelBuilder.Entity("DH_VehicleInventory.Domain.VehicleAggregate.Entities.Inventory", b =>
                {
                    b.HasOne("DH_VehicleInventory.Domain.VehicleAggregate.Entities.Vehicle", "Vehicle")
                        .WithMany("Inventories")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DH_VehicleInventory.Domain.VehicleAggregate.ValueObjects.VehicleStatus", "Status", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("StatusId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("StatusName");

                            b1.HasKey("InventoryId");

                            b1.ToTable("DH_Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("DH_VehicleInventory.Domain.VehicleAggregate.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("LocationId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LocationName");

                            b1.HasKey("InventoryId");

                            b1.ToTable("DH_Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.Navigation("Location");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DH_VehicleInventory.Domain.VehicleAggregate.Entities.Vehicle", b =>
                {
                    b.OwnsOne("DH_VehicleInventory.Domain.VehicleAggregate.ValueObjects.VehicleStatus", "Status", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("StatusId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("StatusName");

                            b1.HasKey("VehicleId");

                            b1.ToTable("DH_Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("DH_VehicleInventory.Domain.VehicleAggregate.ValueObjects.VehicleCode", "VehicleCode", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("VehicleCode");

                            b1.HasKey("VehicleId");

                            b1.ToTable("DH_Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("DH_VehicleInventory.Domain.VehicleAggregate.ValueObjects.VehicleType", "VehicleType", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("VehicleTypeId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("VehicleTypeName");

                            b1.HasKey("VehicleId");

                            b1.ToTable("DH_Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("VehicleCode")
                        .IsRequired();

                    b.Navigation("VehicleType")
                        .IsRequired();
                });

            modelBuilder.Entity("DH_VehicleInventory.Domain.VehicleAggregate.Entities.Vehicle", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
